### ISSUE TITLE
input_number does not seem to be valid in v1.12.0

### ISSUE THREAD

**Issue by danielbrunt57** [custom-cards/slider-button-card#63]
**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.12.0
![image](https://github.com/mattieha/slider-button-card/assets/49846893/15ca9da4-dda6-4b22-9568-d7ad0791dc0e)

**Last working release (if known):**
n/a

**Browser and Operating System:**
MS Edge / Windows 11 Professional

**Description of problem:**
![image](https://github.com/mattieha/slider-button-card/assets/49846893/754c269e-bb4d-40a5-b543-da63ace5f6ec)

**Additional information:**
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: cover.bedroom_blind
        type: custom:multiple-entity-row
        name: Bedroom
        show_state: false
        entities:
          - entity: input_number.bedroom_blind
            name: Preset
          - entity: sensor.bedroom_blind_battery
            name: Battery
          - entity: sensor.bedroom_blind_battery
            name: false
            icon: true
    show_header_toggle: false
    state_color: false
    card_mod:
      class: inline-card
  - type: custom:slider-button-card
    slider:
      direction: bottom-top
      background: gradient
      attribute: tilt
      use_state_color: true
      use_percentage_bg_opacity: true
      toggle_on_click: false
      show_track: true
      force_square: false
      invert: true
    action_button:
      mode: toggle
      show: false
    icon:
      show: false
    entity: cover.bedroom_blind
    show_state: true
    compact: tr
    show_name: false
    name: Bedroom
  - type: custom:slider-button-card
    slider:
      direction: left-right
      background: gradient
      use_state_color: false
      use_percentage_bg_opacity: false
      toggle_on_click: false
      show_track: false
      force_square: false
      invert: false
    icon:
      show: false
    entity: input_number.bedroom_blind
    show_state: true
    compact: true
    show_name: false
    name: Bedroom
```

**Comment by rohankapoorcom** [comment]
Hah - you are fast! You caught me between the merge and the publish & release. I intend to release this tomorrow alongside support for `number` entities.

**Comment by danielbrunt57** [comment]
LOL!  I was flipping back and forth between the main repo and your pull version and wasn't sure where to post, or what my problem was, since the main repo docs showed input_number!  No worries, I'll sleep on it!!

**Comment by danielbrunt57** [comment]
![image](https://github.com/custom-cards/slider-button-card/assets/49846893/c7a262a2-d596-40c4-b57d-d76d07181656)

**Comment by rohankapoorcom** [comment]
Wow. I have no idea why there is a PR from the main branch on custom-cards/slider-button-card back to mattieha/slider-button-card's repo. https://github.com/mattieha/slider-button-card/pull/205. Looks like it's creating a lot of noise in your email!

**Comment by danielbrunt57** [comment]
I don't mind the noise per-se but I'm certainly confused now!  I was originally asked quite some time ago to create a PR for the right-left option, which I did, and left it open but I had no idea how to implement it.  Then you started working on and I'm getting notifications about my PR!  Weird!!

**Comment by danielbrunt57** [comment]
![image](https://github.com/custom-cards/slider-button-card/assets/49846893/415e08af-9c13-4178-b25b-075b41070a49)

**Comment by rohankapoorcom** [comment]
Maybe you picked the wrong branch? It looks like that PR is trying to merge the main branch from this repo into the original repo (mattieha's repo). So every time I merge something into the main branch here, it's getting appended to your PR.

**Comment by rohankapoorcom** [comment]
Going back to your original note in this issue though: I've just pushed out v1.13.0 - https://github.com/custom-cards/slider-button-card/releases/tag/v1.13.0. Once that builds (about 2 minutes), you should be able to test out `input_number` and `number` support!

**Comment by danielbrunt57** [comment]
I got v1.13..0 but still see the same problem...

On Aug 16, 2023 12:34 a.m., Rohan Kapoor ***@***.***> wrote:

Going back to your original note in this issue though: I've just pushed out v1.13.0 - https://github.com/custom-cards/slider-button-card/releases/tag/v1.13.0. Once that builds (about 2 minutes), you should be able to test out input_number and number support!

**Comment by rohankapoorcom** [comment]
Have you confirmed you've cleared your cache? When you load the page with the developer tools in your browser open, it should output the card name and version. Are you seeing v1.13.0 there?

<img width="1478" alt="image" src="https://github.com/custom-cards/slider-button-card/assets/2511957/0b89a9fa-8333-4a0b-9002-f8ee18fc528e">

Here's an example that's working for me: 
<img width="529" alt="image" src="https://github.com/custom-cards/slider-button-card/assets/2511957/e19dccd7-06f8-4f22-aeb6-c1f999b7ce6d">

```
type: custom:slider-button-card
entity: input_number.volume_increment
slider:
  direction: left-right
  background: gradient
  use_state_color: false
  use_percentage_bg_opacity: false
  show_track: false
  toggle_on_click: false
  force_square: false
show_name: true
show_state: true
compact: false
icon:
  show: true
  use_state_color: true
  tap_action:
    action: more-info
  icon: ''
action_button:
  mode: toggle
  icon: mdi:power
  show: true
  show_spinner: true
  tap_action:
    action: toggle
show_attribute: false
name: Input Number Test
```

**Comment by danielbrunt57** [comment]
I had tried shift+reload page, Settings -> Privacy -> Clear browsing data -> Cached images and file,, killed Edge and restarted it 
 but problem persisted.  I just checked Chrome and it's okay.  So this time I did shift+reload page, Settings -> Privacy -> Clear browsing data -> Cached images and files **& also Clear browing data for Internet Explorer -> Temporary internet files**, killed Edge and restarted it and now it's okay.
